apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credential-exposure-admin-oidc
  namespace: gh-leaked-tokens
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: credential-exposure-admin-oidc
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  data:
    - secretKey: client-id
      remoteRef:
        key: credential-exposure-admin-oidc
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: credential-exposure-admin-oidc
        property: client_secret
    - secretKey: allowed-subjects
      remoteRef:
        key: credential-exposure-admin-oidc
        property: allowed_subjects
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credential-exposure-admin-db
  namespace: gh-leaked-tokens
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: credential-exposure-admin-db
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          managed-by: external-secrets
      data:
        DB_URL: "postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@postgres-shared.postgres-operator-deployment.svc.cluster.local:5432/research_gh_leaks"
  data:
    - secretKey: username
      remoteRef:
        key: credential-exposure-admin-db
        property: username
    - secretKey: password
      remoteRef:
        key: credential-exposure-admin-db
        property: password
