apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credential-exposure-study-db
  namespace: gh-leaked-tokens
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: k8s-postgres-credential-exposure
    kind: SecretStore
  target:
    name: credential-exposure-study-db
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          managed-by: external-secrets
      data:
        DB_URL: "postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@postgres-shared.postgres-operator-deployment.svc.cluster.local:5432/research_gh_leaks"
  data:
    - secretKey: username
      remoteRef:
        key: survey-app.postgres-shared.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: password
      remoteRef:
        key: survey-app.postgres-shared.credentials.postgresql.acid.zalan.do
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credential-exposure-reports-db
  namespace: gh-leaked-tokens
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: k8s-postgres-credential-exposure
    kind: SecretStore
  target:
    name: credential-exposure-reports-db
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          managed-by: external-secrets
      data:
        DB_URL: "postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@postgres-shared.postgres-operator-deployment.svc.cluster.local:5432/research_gh_leaks"
  data:
    - secretKey: username
      remoteRef:
        key: disclosure-report-app.postgres-shared.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: password
      remoteRef:
        key: disclosure-report-app.postgres-shared.credentials.postgresql.acid.zalan.do
        property: password
