apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gh-leaked-tokens
resources:
  - db-secret-store.yaml
  - db-external-secrets.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: harbor.i.shion1305.com/shion1305/credential-exposure-study
    newTag: latest
