ipam:
  mode: kubernetes

k8sServiceHost: k8s.shion1305.com
k8sServicePort: 6443

kubeProxyReplacement: true

routingMode: tunnel
tunnelProtocol: vxlan

ipv4:
  enabled: true
ipv6:
  enabled: false

bpf:
  masquerade: true

operator:
  replicas: 1

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: false

cni:
  exclusive: true

policyEnforcementMode: default
