apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Longhorn node configurations
  - node-longhorn-shion-ubuntu-2505.yaml
  - node-longhorn-instance-k8s-proxy.yaml
  # Backup target configuration
  - backup-target.yaml
  # StorageClass definition
  - storageclass.yaml
  # Internal Gateway HTTPRoute for Longhorn UI
  - reference-grant.yaml
  - httproute-internal.yaml
  # Longhorn settings
  - settings.yaml
