apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: instance-k8s-proxy
  namespace: longhorn-system
spec:
  name: instance-k8s-proxy
  allowScheduling: true
  disks:
    hdd-100g-block:
      allowScheduling: true
      diskType: block
      path: /dev/sdb
      tags: ["hdd-ha"]
      # Reserve 1 GiB for system use (in bytes)
      storageReserved: 1073741824
