apiVersion: v1
kind: ServiceAccount
metadata:
  name: renovate-sensor
  namespace: renovate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: renovate-sensor
  namespace: renovate
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: renovate-sensor
  namespace: renovate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: renovate-sensor
subjects:
  - kind: ServiceAccount
    name: renovate-sensor
    namespace: renovate
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: renovate-webhook-trigger
  namespace: renovate
spec:
  template:
    serviceAccountName: renovate-sensor

  dependencies:
    - name: github-event
      eventSourceName: renovate-github
      eventName: renovate

  triggers:
    - template:
        name: renovate-job-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: batch/v1
              kind: Job
              metadata:
                generateName: renovate-webhook-
                namespace: renovate
                labels:
                  app.kubernetes.io/instance: renovate
                  app.kubernetes.io/name: renovate
                  triggered-by: webhook
              spec:
                template:
                  metadata:
                    labels:
                      app.kubernetes.io/instance: renovate
                      app.kubernetes.io/name: renovate
                  spec:
                    serviceAccountName: renovate
                    restartPolicy: Never
                    securityContext:
                      fsGroup: 1000
                      runAsNonRoot: true
                      runAsUser: 1000
                      seccompProfile:
                        type: RuntimeDefault
                    containers:
                      - name: renovate
                        image: ghcr.io/renovatebot/renovate:42.70.0
                        imagePullPolicy: IfNotPresent
                        command:
                          - /bin/bash
                          - /scripts/run-renovate-single.sh
                        env:
                          - name: RENOVATE_CONFIG_FILE
                            value: /usr/src/app/config.json
                          - name: LOG_LEVEL
                            value: info
                          - name: TARGET_REPOSITORY
                            value: ""  # Will be populated by parameter
                          - name: INSTALLATION_ID
                            value: ""  # Will be populated by parameter
                        envFrom:
                          - secretRef:
                              name: renovate-secret
                        resources:
                          limits:
                            cpu: "2"
                            memory: 2Gi
                          requests:
                            cpu: 500m
                            memory: 512Mi
                        volumeMounts:
                          - name: config-volume
                            mountPath: /usr/src/app/config.json
                            subPath: config.json
                          - name: scripts
                            mountPath: /scripts
                    volumes:
                      - name: config-volume
                        configMap:
                          name: renovate-config
                      - name: scripts
                        configMap:
                          name: renovate-scripts
                          defaultMode: 0755
          parameters:
            - src:
                dependencyName: github-event
                dataKey: body.repository.full_name
              dest: spec.template.spec.containers.0.env.2.value
            - src:
                dependencyName: github-event
                dataKey: body.installation.id
              dest: spec.template.spec.containers.0.env.3.value
              operation: append
