apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-db-credentials
  namespace: langfuse
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: langfuse-db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  data:
    - secretKey: DB_USER
      remoteRef:
        key: shared/langfuse
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: shared/langfuse
        property: DB_PASSWORD
