apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-db-credentials
  namespace: langfuse
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: k8s-postgres
    kind: SecretStore
  target:
    name: langfuse-db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  data:
    - secretKey: DB_USER
      remoteRef:
        key: langfuse.postgres-shared.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: langfuse.postgres-shared.credentials.postgresql.acid.zalan.do
        property: password
