apiVersion: v1
kind: ConfigMap
metadata:
  name: freqtrade-config
  namespace: freqtrade
data:
  config.json: |
    {
      "trading_mode": "spot",
      "margin_mode": "",
      "max_open_trades": 5,
      "stake_currency": "USDT",
      "stake_amount": "unlimited",
      "tradable_balance_ratio": 0.99,
      "dry_run": true,
      "dry_run_wallet": 1000,
      "cancel_open_orders_on_exit": false,
      "exchange": {
        "name": "binance",
        "ccxt_sync_config": {},
        "ccxt_async_config": {}
      },
      "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "CORS_origins": []
      },
      "bot_name": "freqtrade",
      "initial_state": "running",
      "internals": {
        "process_throttle_secs": 5
      }
    }
