apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-db-credentials
  namespace: openwebui
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster
    kind: ClusterSecretStore
  target:
    name: openwebui-db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  data:
    - secretKey: DB_USER
      remoteRef:
        key: shared/openwebui
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: shared/openwebui
        property: DB_PASSWORD
