apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-shared
  namespace: postgres-operator-deployment
spec:
  teamId: "default"
  volume:
    size: 1Ti
    storageClass: longhorn-ssd
  numberOfInstances: 1
  users:
    openwebui: []
    langfuse: []
    keycloak: []
  databases:
    openwebui: openwebui
    langfuse: langfuse
    keycloak: keycloak
  postgresql:
    version: "17"
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  patroni:
    pg_hba:
      - local all all trust
      - host all all 0.0.0.0/0 md5
      - hostssl all all 0.0.0.0/0 md5
