apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tt-exporter
  namespace: grafana
  labels:
    app: tt-exporter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tt-exporter
  namespaceSelector:
    matchNames:
      - grafana
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
