apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: k8s-postgres
    kind: SecretStore
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  data:
    - secretKey: username
      remoteRef:
        key: keycloak.postgres-shared.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak.postgres-shared.credentials.postgresql.acid.zalan.do
        property: password
