apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-cluster
    kind: ClusterSecretStore
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  data:
    - secretKey: username
      remoteRef:
        key: shared/keycloak
        property: DB_USER
    - secretKey: password
      remoteRef:
        key: shared/keycloak
        property: DB_PASSWORD
