apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yaml
  - reference-grant.yaml
  - httproute-external.yaml
  - httproute-legacy-redirect.yaml
  - vault-secret-store.yaml
  - db-secret-store.yaml
  - external-secret.yaml
  - zot-realm.yaml
  - grafana-realm.yaml
