apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-keycloak-to-postgres
  namespace: keycloak
spec:
  podSelector:
    matchLabels:
      app: keycloak
  policyTypes:
    - Egress
  egress:
    # Allow egress to postgres-shared in postgres-operator-deployment namespace
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: postgres-operator-deployment
          podSelector:
            matchLabels:
              application: spilo
              cluster-name: postgres-shared
      ports:
        - protocol: TCP
          port: 5432
