apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso
  namespace: keycloak
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: keycloak
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-keycloak"
          serviceAccountRef:
            name: "eso"
