#!/bin/bash
# Secure Keycloak Secret Creation Script
# This script creates the necessary secrets for Keycloak deployment
# Run this script before deploying Keycloak to create secure, random passwords

set -e

NAMESPACE="keycloak"
ADMIN_PASSWORD=$(openssl rand -base64 32)
CLIENT_SECRET=$(openssl rand -base64 32)

echo "Creating Keycloak namespace if it doesn't exist..."
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

echo "Creating admin credentials secret..."
kubectl create secret generic keycloak-admin-credentials \
  --namespace="$NAMESPACE" \
  --from-literal=admin-username=admin \
  --from-literal=admin-password="$ADMIN_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "Creating GHA exchanger credentials placeholder..."
kubectl create secret generic gha-exchanger-credentials \
  --namespace="$NAMESPACE" \
  --from-literal=client-id=gha-exchanger \
  --from-literal=client-secret=placeholder \
  --dry-run=client -o yaml | kubectl apply -f -

echo ""
echo "=== SECURE DEPLOYMENT COMPLETE ==="
echo "Admin username: admin"
echo "Admin password: $ADMIN_PASSWORD"
echo ""
echo "NEXT STEPS FOR GITHUB OAUTH:"
echo "1. Create GitHub OAuth App at: https://github.com/settings/applications/new"
echo "2. Set Authorization callback URL to:"
echo "   https://keycloak.k.shion1305.com/realms/registry/broker/github/endpoint"
echo "3. Create the GitHub OAuth secret:"
echo "   kubectl create secret generic github-oauth-credentials -n keycloak \\"
echo "     --from-literal=client-id=<your-github-oauth-app-client-id> \\"
echo "     --from-literal=client-secret=<your-github-oauth-app-client-secret>"
echo ""
echo "IMPORTANT: Store the admin password securely!"
echo "The GHA client secret will be generated by the bootstrap job."
echo "=================================="