# Keycloak admin credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-30"
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
  admin-username: admin
  admin-password: oHZfzvvfKLnUU1I+wEdCKrjZrNqGNjdt/csZpOwGcqA=

---
# PostgreSQL credentials secret placeholder
# This will be populated by the postgres-secret-replicator job
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-credentials
  namespace: keycloak
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-20"
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  postgres-password: placeholder
  postgres-username: postgres

---
# GitHub Actions exchanger client credentials
# This secret is created manually after the bootstrap job completes
# Contains the client ID and secret for GitHub Actions OIDC token exchange
#
# Example creation command:
# kubectl create secret generic gha-exchanger-credentials -n keycloak \
#   --from-literal=client-id=gha-exchanger \
#   --from-literal=client-secret=<generated-secret>
#
# Current working values:
# - client-id: gha-exchanger  
# - client-secret: dJV7CaroUsFWCeAl2ZBSc5E44odX60uH
