apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-30"
    argocd.argoproj.io/sync-wave: "-3"
    # Skip this resource - create externally
    argocd.argoproj.io/sync-options: Skip
type: Opaque
data:
  # Placeholder - actual secret created externally
  admin-username: YWRtaW4=
  admin-password: cGxhY2Vob2xkZXI=
---
# PostgreSQL credentials secret placeholder
# This will be populated by the postgres-secret-replicator job
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-credentials
  namespace: keycloak
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-20"
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  postgres-password: placeholder
  postgres-username: postgres
---
# GitHub OAuth App credentials for user login
# Create a GitHub OAuth App at: https://github.com/settings/applications/new
# Set Authorization callback URL to: https://keycloak.k.shion1305.com/realms/registry/broker/github/endpoint
#
# SECURITY NOTE: Secrets are NOT stored in Git for security
# Create manually using:
# kubectl create secret generic github-oauth-credentials -n keycloak \
#   --from-literal=client-id=<your-github-oauth-app-client-id> \
#   --from-literal=client-secret=<your-github-oauth-app-client-secret>
apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-credentials
  namespace: keycloak
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-20"
    argocd.argoproj.io/sync-wave: "-2"
    # Skip this resource - create externally
    argocd.argoproj.io/sync-options: Skip
type: Opaque
data:
  # Placeholder - actual secret created externally
  client-id: cGxhY2Vob2xkZXI=
  client-secret: cGxhY2Vob2xkZXI=
