# Keycloak Helm values for registry authentication with external PostgreSQL
auth:
  # Admin credentials are now managed via Kubernetes Secret for security
  existingSecret: keycloak-admin-credentials

# External PostgreSQL configuration
postgresql:
  enabled: false

externalDatabase:
  host: keycloak.postgres-operator-deployment.svc.cluster.local
  port: 5432
  database: keycloak
  user: postgres
  existingSecret: keycloak-postgres-credentials
  existingSecretPasswordKey: postgres-password

# Production settings
production: true
proxy: edge
proxyHeaders: xforwarded

# Security hardening
extraEnvVars:
  - name: KC_FEATURES
    value: "token-exchange"
  - name: KC_HTTP_RELATIVE_PATH
    value: "/"
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "true"
  - name: KC_HTTP_ENABLED
    value: "false"

# Configure ingress
ingress:
  enabled: true
  ingressClassName: nginx-ssl
  hostname: keycloak.k.shion1305.com
  tls: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "32k"


# Resource limits
resources:
  limits:
    memory: 4Gi
    cpu: 4000m
  requests:
    memory: 1500m
    cpu: 500m

# Replica count (can be increased for HA)
replicaCount: 1

# Health checks
livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 10
  successThreshold: 1

# Startup probe to allow for longer initial startup
startupProbe:
  enabled: true
  httpGet:
    path: /realms/master
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 10
  successThreshold: 1

# Service configuration
service:
  type: ClusterIP
  ports:
    http: 8080

# Logging
logging:
  level: INFO

# Cache settings for better performance
cache:
  enabled: true

# JVM settings
extraEnvVarsSecret: ""
javaOpts: "-Xms1g -Xmx1536m -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true"
