apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - reference-grant.yaml
  - httproute-external.yaml
  - grafana.yaml
  - datasource.yaml
  - folders.yaml
  - dashboards.yaml
