apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: shared-app-credentials
spec:
  namespaceSelector:
    matchLabels:
      secrets-sync/enabled: "true"
  refreshTime: 5m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-cluster
      kind: ClusterSecretStore
    target:
      name: shared-app-credentials
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        type: Opaque
        engineVersion: v2
        mergePolicy: Replace
        metadata:
          labels:
            managed-by: external-secrets
    data:
      - secretKey: DB_USER
        remoteRef:
          key: shared/app
          property: DB_USER
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
      - secretKey: DB_PASSWORD
        remoteRef:
          key: shared/app
          property: DB_PASSWORD
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
