apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-github-app
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "github-app-shared"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-github-app"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
