apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: grafana-github-oauth
spec:
  namespaceSelector:
    matchLabels:
      secrets-sync/enabled: "true"
  refreshTime: 5m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-github-app
      kind: ClusterSecretStore
    target:
      name: grafana-github-oauth-secret
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        type: Opaque
        engineVersion: v2
        mergePolicy: Replace
    data:
      - secretKey: dex.github.clientID
        remoteRef:
          key: k8s-at-shion1305-com
          property: clientID
      - secretKey: dex.github.clientSecret
        remoteRef:
          key: k8s-at-shion1305-com
          property: clientSecret
