apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: github-readme-stats
  namespace: external-secrets
spec:
  externalSecretName: github-readme-stats
  namespaceSelector:
    matchLabels:
      secrets-sync/enabled: "true"
  externalSecretSpec:
    secretStoreRef:
      name: vault-cluster
      kind: ClusterSecretStore
    target:
      name: github-readme-stats
      creationPolicy: Owner
    data:
      - secretKey: PAT_1
        remoteRef:
          key: secret/shared/github-readme-stats
          property: github-token
