# Per-namespace RBAC for reading postgres-operator DB credentials.
# Each Role uses resourceNames to restrict access to only that namespace's secret.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-db-langfuse
  namespace: postgres-operator-deployment
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - langfuse.postgres-shared.credentials.postgresql.acid.zalan.do
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-db-langfuse
  namespace: postgres-operator-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-db-langfuse
subjects:
  - kind: ServiceAccount
    name: eso-db
    namespace: langfuse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-db-openwebui
  namespace: postgres-operator-deployment
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - openwebui.postgres-shared.credentials.postgresql.acid.zalan.do
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-db-openwebui
  namespace: postgres-operator-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-db-openwebui
subjects:
  - kind: ServiceAccount
    name: eso-db
    namespace: openwebui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-db-keycloak
  namespace: postgres-operator-deployment
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - keycloak.postgres-shared.credentials.postgresql.acid.zalan.do
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-db-keycloak
  namespace: postgres-operator-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-db-keycloak
subjects:
  - kind: ServiceAccount
    name: eso-db
    namespace: keycloak
