apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso
  namespace: nc-press-chotatsu
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: nc-press-chotatsu
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "nc-press-chotatsu"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-nc-press-chotatsu"
          serviceAccountRef:
            name: "eso"
