apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: clearnet-website-monitoring
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: main-grafana
  title: "Clearnet Website Monitoring"
