apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - vault-secret-store.yaml
  - external-secret.yaml
  - external-secret-browserbase.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - reference-grant.yaml
  - httproute-internal.yaml
  - grafana-folder.yaml
  - grafana-dashboard-pm-fleet.yaml
  - grafana-dashboard-pm-domain.yaml
  - grafana-dashboard-pm-host.yaml
