apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - vault-secret-store.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - grafana-folder.yaml
  - grafana-dashboard.yaml
