apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: provider-monitor
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: main-grafana
  title: "Provider Monitor"
