apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: whisper-api-key
  namespace: whisper
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 48
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whisper-api-key
  namespace: whisper
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  target:
    name: whisper-api-key
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: whisper
          app.kubernetes.io/managed-by: external-secrets
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: whisper-api-key
