apiVersion: v1
kind: Service
metadata:
  name: network-stress-test-service
  namespace: network-stress-test
  labels:
    app: network-stress-test
spec:
  selector:
    app: network-stress-test
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: network-stress-test-nodeport
  namespace: network-stress-test
  labels:
    app: network-stress-test
spec:
  selector:
    app: network-stress-test
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30808
    protocol: TCP
  type: NodePort
