apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: local-storage
data:
  storageClassMap: |
    local-storage:
       hostDir: /var/local-storage
       mountDir: /var/local-storage
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
