apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-pvc-storage-limits
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: limit-pvc-size-globally
    match:
      any:
      - resources:
          kinds:
          - PersistentVolumeClaim
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - kube-public
          - kube-node-lease
          - kyverno
    # Exclude Longhorn storage classes from PVC size limits
    preconditions:
      any:
      - key: "{{ request.object.spec.storageClassName || '' }}"
        operator: NotIn
        value: ['longhorn', 'longhorn-hdd', 'longhorn-ssd', 'longhorn-static']
    validate:
      message: "PVC size exceeds maximum allowed (100Gi). Large storage requests can cause node capacity issues."
      pattern:
        spec:
          resources:
            requests:
              storage: "<=100Gi"
