apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: gh-leaked-tokens
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: main-grafana
  title: "GH Leaked Tokens"
