apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-leaked-tokens-db-grafana
  namespace: grafana
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: k8s-postgres-gh-leaked-tokens
    kind: SecretStore
  target:
    name: gh-leaked-tokens-db-grafana
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  data:
    - secretKey: username
      remoteRef:
        key: research-gh-leaks.postgres-shared.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: password
      remoteRef:
        key: research-gh-leaks.postgres-shared.credentials.postgresql.acid.zalan.do
        property: password
