apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-secret-store.yaml
  - db-external-secret.yaml
  - vault-secret-store.yaml
  - healthcheck-external-secret.yaml
  - pushgateway.yaml
  - prometheus.yaml
  - servicemonitor.yaml
  - cronjob.yaml
  - grafana-db-secret-store.yaml
  - grafana-db-external-secret.yaml
  - grafana-datasource.yaml
  - grafana-datasource-postgres.yaml
  - grafana-folder.yaml
  - grafana-dashboard.yaml
  - grafana-dashboard-by-provider.yaml
  - grafana-dashboard-provider-detail.yaml
