apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-secret-store.yaml
  - db-external-secret.yaml
  - pushgateway.yaml
  - servicemonitor.yaml
  - cronjob.yaml
