# Secret replication using Kubernetes Job with proper RBAC
# This approach securely copies the secret without exposing credentials in GitOps

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-replicator
  namespace: airbyte
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-20"
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-replicator
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-20"
    argocd.argoproj.io/sync-wave: "-2"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["update", "patch"]
  resourceNames: ["airbyte-airbyte-secrets", "airbyte-auth-secrets"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-replicator
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-20"
    argocd.argoproj.io/sync-wave: "-2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-replicator
subjects:
- kind: ServiceAccount
  name: secret-replicator
  namespace: airbyte
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-secret-replicator
  namespace: airbyte
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      serviceAccountName: secret-replicator
      restartPolicy: OnFailure
      containers:
      - name: secret-replicator
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Creating Airbyte-compatible secret from PostgreSQL credentials..."
          
          # Check if source secret exists
          if ! kubectl get secret airbyte.airbyte.credentials.postgresql.acid.zalan.do -n postgres-operator-deployment >/dev/null 2>&1; then
            echo "Source secret not found in postgres-operator-deployment namespace"
            exit 1
          fi
          
          # Get the password from the source secret
          PASSWORD=$(kubectl get secret airbyte.airbyte.credentials.postgresql.acid.zalan.do -n postgres-operator-deployment -o jsonpath='{.data.password}')
          
          # Update the existing Airbyte secret (managed by ArgoCD) with the correct values
          kubectl patch secret airbyte-config-secrets -n airbyte --type='json' -p='[
            {"op":"replace","path":"/data/database-password","value":"'"$PASSWORD"'"}
          ]'
      activeDeadlineSeconds: 300
  backoffLimit: 10
