apiVersion: v1
kind: Secret
metadata:
  name: airbyte-config-secrets
  namespace: airbyte
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-20"
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  database-user: airbyte
  database-password: placeholder
