# Secret replication using Kubernetes Job with proper RBAC
# This approach securely copies the secret without exposing credentials in GitOps

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-replicator
  namespace: airbyte
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-replicator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["airbyte.airbyte.credentials.postgresql.acid.zalan.do"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-replicator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-replicator
subjects:
- kind: ServiceAccount
  name: secret-replicator
  namespace: airbyte
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-secret-replicator
  namespace: airbyte
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: secret-replicator
      restartPolicy: OnFailure
      containers:
      - name: secret-replicator
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Replicating PostgreSQL secret to airbyte namespace..."
          
          # Check if source secret exists
          if ! kubectl get secret airbyte.airbyte.credentials.postgresql.acid.zalan.do -n postgres-operator-deployment >/dev/null 2>&1; then
            echo "Source secret not found in postgres-operator-deployment namespace"
            exit 1
          fi
          
          # Get the secret and replicate it
          kubectl get secret airbyte.airbyte.credentials.postgresql.acid.zalan.do -n postgres-operator-deployment -o yaml | \
            sed 's/namespace: postgres-operator-deployment/namespace: airbyte/' | \
            sed '/resourceVersion:/d' | \
            sed '/uid:/d' | \
            sed '/creationTimestamp:/d' | \
            kubectl apply -f -
          
          echo "Secret replicated successfully"
      activeDeadlineSeconds: 300
  backoffLimit: 3
