apiVersion: v1
kind: Service
metadata:
  name: postgres-operator-ui
  namespace: postgres-operator
  labels:
    app: postgres-operator-ui
spec:
  selector:
    app: postgres-operator-ui
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  type: ClusterIP
