image:
  registry: registry.opensource.zalan.do
  repository: acid/postgres-operator
  tag: v1.14.0
  pullPolicy: IfNotPresent

# Operator configuration
configGeneral:
  enable_crd_registration: true
  enable_lazy_spilo_upgrade: false
  enable_pgversion_env_var: true
  enable_shm_volume: true
  enable_spilo_wal_path_compat: false
  enable_team_superuser: false
  etcd_host: ""
  kubernetes_use_configmaps: false
  spilo_runasuser: 101
  spilo_runasgroup: 103
  spilo_fsgroup: 103

configConnectionPooler:
  connection_pooler_image: "registry.opensource.zalan.do/acid/pgbouncer:master-32"
  connection_pooler_max_db_connections: 60
  connection_pooler_mode: "transaction"
  connection_pooler_number_of_instances: 2
  connection_pooler_schema: "pooler"
  connection_pooler_user: "pooler"

configDebug:
  debug_logging: true
  enable_database_access: true

configTeamsApi:
  enable_teams_api: false
  enable_team_superuser: false
  enable_admin_role_for_users: true

configKubernetes:
  cluster_domain: "cluster.local"
  cluster_labels:
    application: spilo
  cluster_name_label: "cluster-name"
  enable_cross_namespace_secret: false
  enable_init_containers: true
  enable_pod_antiaffinity: false
  enable_pod_disruption_budget: true
  enable_sidecars: true
  master_pod_move_timeout: "20m"
  node_readiness_label: {}
  node_readiness_label_merge: "OR"
  oauth_token_secret_name: "postgresql-operator"
  pdb_name_format: "postgres-{cluster}-pdb"
  pod_deletion_wait_timeout: "10m"
  pod_label_wait_timeout: "10m"
  pod_management_policy: "ordered_ready"
  pod_role_label: "spilo-role"
  pod_service_account_definition: ""
  pod_service_account_name: "postgres-pod"
  pod_service_account_role_binding_definition: ""
  pod_terminate_grace_period: "5m"
  spilo_privileged: false
  storage_resize_mode: "pvc"
  watched_namespace: "*"  # Watch all namespaces

configLogicalBackup:
  logical_backup_docker_image: "registry.opensource.zalan.do/acid/logical-backup:v1.14.0"
  logical_backup_job_prefix: "logical-backup-"
  logical_backup_provider: "s3"
  logical_backup_s3_bucket: ""
  logical_backup_s3_endpoint: ""
  logical_backup_s3_region: ""
  logical_backup_s3_secret_name: ""
  logical_backup_schedule: "30 00 * * *"

configPostgreSQL:
  docker_image: "registry.opensource.zalan.do/acid/spilo-16:3.3-p1"
  enable_master_load_balancer: false
  enable_master_pooler_load_balancer: false
  enable_replica_load_balancer: false
  enable_replica_pooler_load_balancer: false
  master_dns_name_format: "{cluster}.{namespace}.svc.cluster.local"
  replica_dns_name_format: "{cluster}-repl.{namespace}.svc.cluster.local"

# Resource limits for the operator
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 250Mi

# RBAC
rbac:
  create: true
  createAggregateClusterRoles: false

serviceAccount:
  create: true

# Enable CRD registration
enableJsonLogging: false
