apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gmo-coin-api-secret
  namespace: atc
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: gmo-coin-api-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  dataFrom:
    - extract:
        key: atc/gmo-coin-api-secret
