apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - tlsroute-internal.yaml
  - ws-stream-deployment.yaml
  - mcp-connector.yaml
  - network-policy-mcp-to-postgres.yaml
  - reference-grant.yaml
  - grafana-config.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-httproute.yaml
  - prometheus.yaml
  - prometheus-httproute.yaml
  - vault-secret-store.yaml
  - external-secret.yaml
  - deployment-gmocoin-exec-alert.yaml
  - reprice-deployment.yaml
  - seaweedfs-external-secret.yaml
  - seaweedfs-statefulset.yaml
  - seaweedfs-service.yaml
  - seaweedfs-httproute.yaml
  - network-policy-openwebui-to-mcp.yaml
  - network-policy-to-postgres.yaml
