apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-historical-source-credentials
  namespace: atc
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: seaweedfs-historical-source-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
      data:
        s3.config.json: |
          {
            "identities": [
              {
                "name": "admin",
                "credentials": [
                  {
                    "accessKey": "{{ .S3_ACCESS_KEY }}",
                    "secretKey": "{{ .S3_SECRET_KEY }}"
                  }
                ],
                "actions": [
                  "Admin",
                  "Read",
                  "List",
                  "Tagging",
                  "Write"
                ]
              }
            ]
          }
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: seaweedfs-historical-source
        property: S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: seaweedfs-historical-source
        property: S3_SECRET_KEY
