apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - redis.yaml
  - deployment.yaml
  - reference-grant.yaml
  - httproute-external.yaml
  - vault-secret-store.yaml
  - external-secret.yaml
  - db-secret-store.yaml
  - external-secret-db.yaml
