apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-internal-controller.yaml
  - nginx-ssl-controller.yaml
  - ssl-cert-renewal-cronjob.yaml
  - network-policy-allow-ingress.yaml
