apiVersion: batch/v1
kind: CronJob
metadata:
  name: heartbeat-shion-ubuntu-2505
  namespace: node-healthcheck
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          tolerations:
          - operator: Exists
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - shion-ubuntu-2505
          containers:
          - name: ping
            image: curlimages/curl:8.10.1
            args:
            - "-fsS"
            - "$(HEALTHCHECK_URL)"
            env:
            - name: HEALTHCHECK_URL
              valueFrom:
                secretKeyRef:
                  name: node-healthcheck-urls
                  key: shion-ubuntu-2505-url