apiVersion: batch/v1
kind: CronJob
metadata:
  name: heartbeat-raspi-cm4
  namespace: node-healthcheck
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      backoffLimit: 0
      template:
        spec:
          terminationGracePeriodSeconds: 5
          restartPolicy: Never
          # Use host network for raspberry pi
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          tolerations:
            - operator: Exists
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - raspi-cm4
          containers:
            - name: ping
              image: nicolaka/netshoot:v0.14
              command: ["/bin/sh", "/scripts/healthcheck.sh"]
              env:
                - name: HEALTHCHECK_URL
                  valueFrom:
                    secretKeyRef:
                      name: node-healthcheck-urls
                      key: raspi-cm4-url
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
          volumes:
            - name: script
              configMap:
                name: healthcheck-script
                defaultMode: 0555
