apiVersion: batch/v1
kind: CronJob
metadata:
  name: heartbeat-instance-k8s-proxy
  namespace: node-healthcheck
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      backoffLimit: 0
      template:
        spec:
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          terminationGracePeriodSeconds: 5
          restartPolicy: Never
          tolerations:
            - operator: Exists
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - instance-k8s-proxy
          containers:
            - name: ping
              image: nicolaka/netshoot:v0.15
              command: ["/bin/sh", "/scripts/healthcheck.sh"]
              env:
                - name: HEALTHCHECK_URL
                  valueFrom:
                    secretKeyRef:
                      name: node-healthcheck-urls
                      key: instance-k8s-proxy-url
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
          volumes:
            - name: script
              configMap:
                name: healthcheck-script
                defaultMode: 0555
