apiVersion: batch/v1
kind: CronJob
metadata:
  name: heartbeat-instance-2024-1
  namespace: node-healthcheck
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      backoffLimit: 0
      template:
        spec:
          terminationGracePeriodSeconds: 5
          # Never restart failed pods so they remain for log inspection
          restartPolicy: Never
          tolerations:
            - operator: Exists
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - instance-2024-1
          containers:
            - name: ping
              image: curlimages/curl:8.17.0
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -eu

                  # 4 total attempts, 2s delay between attempts
                  for i in 1 2 3 4; do
                    echo "Attempt $i: curling $HEALTHCHECK_URL" >&2

                    # Keep or remove -v depending on how noisy you want logs to be.
                    if curl -fsSv \
                        --max-time 15 \
                        "$HEALTHCHECK_URL"
                    then
                      exit 0
                    fi

                    sleep 2
                  done

                  exit 1
              env:
                - name: HEALTHCHECK_URL
                  valueFrom:
                    secretKeyRef:
                      name: node-healthcheck-urls
                      key: instance-2024-1-url