apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso
  namespace: github-readme-stats
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: github-readme-stats
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "github-readme-stats"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-github-readme-stats"
          serviceAccountRef:
            name: "eso"
