apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-hdd
  resources:
    requests:
      storage: 50Gi
