backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: "postgres-shared.postgres-operator-deployment.svc.cluster.local"
    port: 5432
    database: "mlflow"
    driver: "psycopg2"
  existingDatabaseSecret:
    name: "mlflow-db-credentials"
    usernameKey: "DB_USER"
    passwordKey: "DB_PASSWORD"

artifactRoot:
  defaultArtifactRoot: "/mlflow/artifacts"

extraVolumes:
  - name: mlflow-artifacts
    persistentVolumeClaim:
      claimName: mlflow-artifacts

extraVolumeMounts:
  - name: mlflow-artifacts
    mountPath: /mlflow/artifacts

extraEnvVars:
  MLFLOW_SERVER_ALLOWED_HOSTS: "mlflow.k.shion1305.com"

ingress:
  enabled: false

postgresql:
  enabled: false

mysql:
  enabled: false
