apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  # Deploy before other apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    path: argocd-rbac/core
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false  # Never auto-prune RBAC resources for safety
      selfHeal: true  # Auto-restore if deleted or modified
    syncOptions:
      - CreateNamespace=false
      - Replace=true  # Use replace strategy for cluster-scoped resources
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
