apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.0.5  # ArgoCD v3.1.9
      helm:
        valueFiles:
          - $values/argocd/values.yaml
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
