apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-monitoring
  namespace: argocd
spec:
  project: default
  sources:
  # Cloudflare Exporter
  - repoURL: https://lablabs.github.io/cloudflare-exporter
    chart: cloudflare-exporter
    targetRevision: 0.0.3
    helm:
      releaseName: cloudflare-exporter
      valueFiles:
      - $values/cloudflare-exporter/values.yaml
  # Grafana for Cloudflare
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.5.2
    helm:
      releaseName: cloudflare-grafana
      valueFiles:
      - $values/cloudflare-exporter/grafana-values.yaml
  # Values reference
  - repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    ref: values
  # Additional resources (ServiceMonitor, Ingress)
  - repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    path: cloudflare-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
