apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    path: github-actions-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: github-actions-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
