apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-pull-source
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    path: harbor-pull-source
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor-pull-source
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
