apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    path: keycloak-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
