apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    path: storage
  destination:
    server: https://kubernetes.default.svc
    namespace: local-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
