apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nc-press-chotatsu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    path: nc-press-chotatsu
  destination:
    server: https://kubernetes.default.svc
    namespace: nc-press-chotatsu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
