apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      targetRevision: 4.39.0
      helm:
        valueFiles:
          - $values/node-exporter/values.yaml
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      path: node-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: node-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
