apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
      chart: postgres-operator
      targetRevision: 1.14.0
      helm:
        valueFiles:
          - $values/postgres-operator/values.yaml
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      path: postgres-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
