apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
      chart: postgres-operator
      targetRevision: 1.14.0
      helm:
        values: |
          operator:
            namespace: postgres-operator
    - repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
      chart: postgres-operator-ui
      targetRevision: 1.14.0
      helm:
        values: |
          operatorApi:
            url: http://postgres-operator:8080
