apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privacy-focused-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shion1305/k8s-GitOps.git
    targetRevision: HEAD
    path: privacy-focused-gateway/
  destination:
    server: https://kubernetes.default.svc
    namespace: privacy-focused-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
