apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/renovatebot/charts
      chart: renovate
      targetRevision: 46.44.3
      helm:
        valueFiles:
          - $values/renovate/values.yaml
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      ref: values
    # ConfigMap with wrapper script
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      path: renovate
      directory:
        include: scripts-configmap.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
