apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vald
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://vald.vdaas.org/charts
      chart: vald
      targetRevision: 1.7.0
      helm:
        valueFiles:
          - $values/vald/values.yaml
    - repoURL: https://github.com/Shion1305/k8s-GitOps.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vald
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
