apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-secret-store.yaml
  - external-secret.yaml
  - vault-secret-store.yaml
  - config.yaml
  - deployment.yaml
  - httproute-internal.yaml
  - reference-grant.yaml
