apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policy-to-mcp.yaml
  - network-policy-mongodb.yaml
  - network-policy-from-ingress.yaml
  - ingress.yaml
