auth:
  postgresPassword: "postgres123"
  username: "airbyte"
  password: "airbyte123"
  database: "airbyte"

primary:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-storage
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

postgresql:
  maxConnections: 200
