apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - servicemonitor.yaml
  - reference-grant.yaml
  - grafana-httproute.yaml
  - grafana-ingress.yaml
  - grafana.yaml
  - grafana-datasource.yaml
  - grafana-folder.yaml
  - grafana-dashboards.yaml
  - vault-secret-store.yaml
  - external-secret.yaml
